<a href="https://colab.research.google.com/github/Romneasek/Numpy_Mini_Project/blob/main/Numpy_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
path = '/content/makeSenseOfCensus.csv'
data = np.genfromtxt(path, delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)



Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [6]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [7]:
new_record = [[50, 9, 4, 1, 0, 0, 40, 0]]
np.concatenate((data, new_record), axis = 0)

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [8]:
age = np.array(data[:,0])
print(age)

[39. 50. 38. 53. 28. 37. 49. 52. 31. 42. 37. 30. 23. 32. 40. 34. 25. 32.
 38. 43. 40. 54. 35. 43. 59. 56. 19. 54. 39. 49. 23. 20. 45. 30. 22. 48.
 21. 19. 31. 48. 31. 53. 24. 49. 25. 57. 53. 44. 41. 29. 25. 18. 47. 50.
 47. 43. 46. 35. 41. 30. 30. 32. 48. 42. 29. 36. 28. 53. 49. 25. 19. 31.
 29. 23. 79. 27. 40. 67. 18. 31. 18. 52. 46. 59. 44. 53. 49. 33. 30. 43.
 57. 37. 28. 30. 34. 29. 48. 37. 48. 32. 76. 44. 47. 20. 29. 32. 17. 30.
 31. 42. 24. 38. 56. 28. 36. 53. 56. 49. 55. 22. 21. 40. 30. 29. 19. 47.
 20. 31. 35. 39. 28. 24. 38. 37. 46. 38. 43. 27. 20. 49. 61. 27. 19. 45.
 70. 31. 22. 36. 64. 43. 47. 34. 33. 21. 52. 48. 23. 71. 29. 42. 68. 25.
 44. 28. 45. 36. 39. 46. 18. 66. 27. 28. 51. 27. 28. 27. 21. 34. 18. 33.
 44. 43. 30. 40. 37. 34. 41. 53. 31. 58. 38. 24. 41. 47. 41. 23. 36. 40.
 35. 24. 26. 19. 51. 42. 37. 18. 36. 35. 58. 17. 44. 37. 35. 60. 54. 37.
 50. 38. 45. 25. 31. 64. 90. 54. 53. 18. 60. 66. 75. 65. 35. 41. 25. 33.
 28. 59. 40. 41. 38. 23. 40. 41. 24. 20. 38. 56. 58

In [9]:
max_age = np.max(age)
min_age = np.min(age)
age_mean = np.mean(age)
age_std = np.std(age)
print(max_age)
print(min_age)
print(age_mean)
print(age_std)

90.0
17.0
38.051
13.342803266180612


In [10]:
race = np.array(data[:,2])
print(race)

[4. 4. 4. 2. 2. 4. 2. 4. 4. 4. 2. 1. 4. 2. 1. 0. 4. 4. 4. 4. 4. 2. 2. 4.
 4. 4. 4. 1. 4. 4. 4. 2. 4. 4. 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4.
 4. 4. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 1. 4. 4.
 4. 4. 4. 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4.
 4. 4. 2. 4. 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 4. 1. 4. 4. 4. 4.
 4. 2. 4. 4. 4. 4. 4. 4. 1. 4. 4. 4. 4. 2. 4. 2. 4. 4. 1. 1. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 2. 2. 4. 4. 2. 4. 2. 4. 4. 2. 4. 4. 4. 4. 2. 4.
 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 2. 4. 0. 1. 4. 2.
 4. 4. 4. 4. 4. 4. 2. 2. 4. 4. 0. 4. 4. 4. 2. 2. 4. 3. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 2. 4. 4. 1. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 1. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 2. 4. 4. 1. 4. 4. 4. 1. 4. 4. 1. 4. 4. 4. 4. 4. 4. 1.
 2. 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4.

In [11]:
race_0 = np.array(race[race == 0])
race_1 = np.array(race[race == 1])
race_2 = np.array(race[race == 2])
race_3 = np.array(race[race == 3])
race_4 = np.array(race[race == 4])
print(race_0)
print(race_1)
print(race_2)
print(race_3)
print(race_4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4

In [12]:
len_0 =len(race_0)
len_1 =len(race_1)
len_2 =len(race_2)
len_3 =len(race_3)
len_4 =len(race_4)

print(len(race_0))
print(len(race_1))
print(len(race_2))
print(len(race_3))
print(len(race_4))

10
27
110
6
847


In [13]:
minority_race = min(len_0, len_1, len_2, len_3, len_4)
print(minority_race)

6


In [14]:
senior_citizens = np.array(age[age>60])
print(senior_citizens)

[79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]


In [15]:
working_hour_sum =np.sum(data[:,6])
print(working_hour_sum)

39876.0


In [16]:
senior_citizens_len = len(senior_citizens)
print(senior_citizens_len)

61


In [17]:
avg_working_hours = working_hour_sum / senior_citizens_len
print(avg_working_hours)

653.7049180327868


In [18]:
education_num = np.array(data[:,1])
print(education_num)

[13. 13.  9.  7. 13. 14.  5.  9. 14. 13. 10. 13. 13. 12. 11.  4.  9.  9.
  7. 14. 16.  9.  5.  7.  9. 13.  9. 10.  9.  9. 12. 10. 13. 10. 10.  7.
 10.  9. 10. 12.  5. 13. 13.  9.  9. 13.  9. 14. 11. 11. 10.  9. 15. 13.
  9. 10.  3. 11.  9.  9. 13.  4.  9. 16. 10.  9. 10.  9. 10. 10. 10. 13.
 13. 10. 10.  9. 12.  6.  7.  4.  9. 13.  9.  9.  9.  9.  9. 14.  5. 16.
 11. 10. 10.  9. 13. 10. 16. 10. 12.  9. 14. 13. 14. 10.  9.  9.  6.  7.
  9.  9. 13. 15.  9. 10.  9.  5. 10. 11. 10.  9. 10. 13. 13. 13. 10. 13.
 10. 12.  9. 10. 12.  9.  9. 13. 12. 14.  9. 11. 10. 10.  9. 10. 10. 11.
 10.  9. 10.  9.  7. 10. 10.  9. 13.  9.  9.  9. 13. 10.  9. 13.  2.  9.
 14.  9. 14. 10. 12. 14.  7. 11.  9.  9. 10. 13. 13.  9.  9.  9.  9. 13.
 10. 10. 10.  4. 10.  9. 13. 13. 14. 16. 10. 10. 13. 10. 13.  3. 10. 14.
 14.  9. 14.  9. 13. 10.  9.  7. 13.  9.  9.  7.  9.  9. 10.  9.  4. 13.
 12. 13. 13.  6. 10.  2.  9.  9.  1.  9.  6.  9. 11.  9.  7.  9. 10. 10.
 15.  9. 10. 13. 14.  9. 13.  9. 12. 10. 10.  9.  9

In [19]:
high = np.array(education_num[education_num >10])
low = np.array(education_num[education_num <=10])
print(high)
print(low)

[13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13. 13. 16. 13. 13. 13. 11. 13.
 13. 13. 13. 13. 11. 11. 13. 13. 14. 11. 13. 13. 13

In [20]:
income = np.array(data[:,7])
print(income)

[0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.
 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0.
 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.

In [24]:
avg_pay_high = np.mean(income[education_num > 10])
print('Average pay high:',avg_pay_high)
avg_pay_low = np.mean(income[education_num <= 10])
print('Average pay low',avg_pay_low)

Average pay high: 0.42813455657492355
Average pay low 0.13670133729569092


In [25]:
income[education_num > 10]

array([0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 0., 1., 1., 0.